spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ANIKET
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: Aniketadvancedjava@gmail.com
    password: Akki@123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
server:
  port: 9090     
